<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>startup_Button</name>
   <tag></tag>
   <elementGuidId>fa2960ed-3ad3-4fd3-8123-bd9b3df3c415</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//*[@id='add-your-menu']/*)[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//*[@id='add-your-menu']/*)[2]</value>
   </webElementProperties>
</WebElementEntity>
